swagger: "2.0"
info:
  description: "sistema de pedidos online para un restaurante [http://localhost:3000/v1/api/]"
  version: "1.0.0"
  title: "Delilah Restó"
  termsOfService: "http://localhost:3000/v1/api/"
  contact:
    email: "user@consorcios.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/v1/api"
tags:

- name: "users"
  description: "Operaciones CRUD users"
  externalDocs:
    description: "Documentacion externa users"
    url: "http://localhost:3000/v1/api/users"
    
- name: "meals"
  description: "Operaciones CRUD meals"
  externalDocs:
    description: "Documentacion externa de meals"
    url: "http://localhost:3000/v1/api/meals"
    
- name: "orders"
  description: "Operaciones CRUD orders"
  externalDocs:
    description: "Documentacion externa de orders"
    url: "http://localhost:3000/v1/api/orders"
schemes:
- "http"

paths:
  /register:
    post:
      tags:
      - "users"
      summary: "Crea un nuevo usuario"
      description: ""
      operationId: "Nuevo Usuario"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto user para crear un usuario"
        required: true
        schema:
          $ref: "#/definitions/usersRegister"
      responses:
        "201":
           description: "Usuario Creado"
        "400":
          description: "Usuario ya existe"
        "500":
          description: "Error inesperado"
          
  /login:
    post:
      tags:
      - "users"
      summary: "Login de un usuario"
      description: ""
      operationId: "indentificar usuario"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto para iniciar sesión en la app"
        required: true
        schema:
          $ref: "#/definitions/usersLogin"
      responses:
        "200":
          description: 'Usuario verficado'
        "400":
          description: "Usuario y/o contraseña inválida"
        "500":
          description: "Error inesperado"
          
  /users:
    get:
      tags:
      - "users"
      summary: "Obtener todos los usuarios"
      description: "Obtener todos los usuarios"
      operationId: "Obtener todos los usuarios"
      produces:
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: ""
        required: true
        type: "array"
        items:
          type: "string"
          enum:
          - "available"
          - "pending"
          - "sold"
          default: "available"
        collectionFormat: "multi"
      responses:
        "200":
          description: "Operacion Realizada"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/users"
        "404":
          description: "Usuarios no encontrados"
        "500":
          description: "Error inesperado"
    post:
      tags:
      - "users"
      summary: "Crea un nuevo usuario"
      description: ""
      operationId: "NuevoUsuario"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Objeto user para crear un usuario"
        required: true
        schema:
          $ref: "#/definitions/usersRegister"
      responses:
        "201":
          description: "Usuario Creado"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/users"
        "400":
          description: "Usuario ya existe"
        "500":
          description: "Error inesperado"

  /users/{userId}:
    get:
      tags:
      - "users"
      summary: "Busco un usuario por Id"
      description: "Retorno un usuario"
      operationId: "obtenerUsuarioPorId"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "userId"
        in: "path"
        description: "Identifica el id del propietario"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Operacion Realizada"
          schema:
            $ref: "#/definitions/users"
        "404":
          description: "Usuarios no encontrados"
        "500":
          description: "Error inesperado"
          
    put:
      tags:
      - "users"
      summary: "Modifico el rol del usuario"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "usersId"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
        schema:
          $ref: "#/definitions/userStatus"
      responses:
        "204":
          description: "user actulizado"
        "400":
          description: "error en la actualización"
        "500":
          description: "Error inesperado"

    delete:
      tags:
      - "users"
      summary: "Elimino a un usuario"
      description: ""
      operationId: "eliminarUsuario"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "usersId"
        in: "path"
        description: "Eliminar usuario identificado"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "user eliminado"
        "500":
          description: "Error inesperado"
          
  /meals:
    post:
      tags:
      - "meals"
      summary: "Crea un nuevo plato"
      description: ""
      operationId: "NuevoPlato"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Objeto user para crear un nuevo plato"
        required: true
        schema:
          $ref: "#/definitions/meals"
      responses:
        "201":
          description: "Plato creado"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/meals"
        "400":
          description: "error en la creación"
        "500":
          description: "Error inesperado"
    get:
      tags:
      - "meals"
      summary: "Obtener todos los platos"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: ""
        required: true
        type: "array"
        items:
          type: "string"
          enum:
          - "available"
          - "pending"
          - "sold"
          default: "available"
        collectionFormat: "multi"
      responses:
        "200":
          description: "Operacion Realizada"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/meals"
        "404":
          description: "error en la búsqueda"
        "500":
          description: "Error inesperado"
  
  /meals/{mealsId}:
    get:
      tags:
      - "users"
      summary: "Busco un plato por Id"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "mealsId"
        in: "path"
        description: "Identifica el id del propietario"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Operacion Realizada"
          schema:
            $ref: "#/definitions/meals"
        "404":
          description: "error en la búsqueda"
        "500":
          description: "Error inesperado"
          
    put:
      tags:
      - "meals"
      summary: "Modifico el plato de comida"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "mealsId"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
        schema:
          $ref: "#/definitions/meals"
      responses:
        "204":
          description: "plato actulizado"
        "400":
          description: "error en la actualización"
        "500":
          description: "Error inesperado"
          
    delete:
      tags:
      - "meals"
      summary: "Elimina un plato"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "mealsId"
        in: "path"
        description: "Eliminar plato"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "plato eliminado"
        "500":
          description: "Error inesperado"
          
  /orders:
    get:
      tags:
      - "orders"
      summary: "Obtener todas las órdenes"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "orders"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Operacion Realizada"
          schema:
            $ref: "#/definitions/orders"
        "404":
          description: "Usuarios no encontrados"
        "500":
          description: "Error inesperado"
          
    post:
      tags:
      - "orders"
      summary: "Crea una nueva orden"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Objeto para crea una nueva orden"
        required: true
        schema:
          $ref: "#/definitions/orders"
      responses:
        "201":
          description: "Orden creada"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/orders"
        "400":
          description: "error en la creación"
        "500":
          description: "Error inesperado"
  
  /orders/{orderId}:
    put:
      tags:
      - "orders"
      summary: "Modifico el plato de comida"
      description: ""
      operationId: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "orderId"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
        schema:
          $ref: "#/definitions/orderStatus"
      responses:
        "204":
          description: "orden actulizado"
        "400":
          description: "error en la actualización"
        "500":
          description: "Error inesperado"
    delete:
      tags:
      - "orders"
      summary: "Elimina una orden"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "mealsId"
        in: "path"
        description: "Eliminar orden"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "orden eliminada"
        "500":
          description: "Error inesperado"
          
  /orders/user:
    get:
      tags:
      - "orders"
      summary: "Obtener todas las órdenes de un usuario"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "orders"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Operacion Realizada"
          schema:
            $ref: "#/definitions/orders"
        "404":
          description: "orden no encontrados"
        "500":
          description: "Error inesperado"
  
definitions:
  usersRegister:
    type: "object"
    properties:
      id_user:
        type: "integer"
        format: "int64"
      nombre_user:
        type: "string"
      email:
        type: "string"
      contrasena:
        type: "string"
      phone:
        type: "string"
      address:
        type: "string"
      id_role:
        type: "integer"
        format: "int32"
      
  usersLogin:
    type: "object"
    properties:
      email:
        type: "string"
      contrasena:
        type: "string"
      
  users:
    type: "object"
    properties:
      id_user:
        type: "integer"
        format: "int64"
      nombre_user:
        type: "string"
      email:
        type: "string"
      contrasena:
        type: "string"
      phone:
        type: "string"
      address:
        type: "string"
      id_role:
        type: "integer"
        format: "int32"
        
  userStatus:
    type: "object"
    properties:
       id_role:
          type: "integer"
          format: "int32"
          
  meals:
    type: 'object'
    properties:
      nombre_meal:
        type: 'string'
      precio: 
        type: "integer"
        format: "int32"
      img:
        type: 'string'
        
  orders:
    type: 'object'
    properties:
      id_user:
        type: "integer"
        format: "int32"
      id_meal:
        type: "integer"
        format: "int32"
      id_forma_pago:
        type: "integer"
        format: "int32"
      id_status:
        type: "integer"
        format: "int32"
        
  orderStatus:
    type: "object"
    properties:
       id_status:
          type: "integer"
          format: "int32"
      

        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"